### ISSUE TITLE
Slashes were added to the survey-Link

### ISSUE THREAD

**Issue by ralli13** [SondagesPro/LS-sendMailCron#4]
If i put https://somedomain.tld ind the hostinfoUrl and /index.php in the ScriptUrl, i get {surveylinks} that looks like this:

`https:\/\/somedomain.tld/\/index.php........`

which leads to an Page not found. Interesting is that the first block `https:\/\/` is replaced by the browser to `\\ `but the second part with the `/\/ `is replaced to `///`.

Workaround is to set the hostinfourl to www.somedomain.tld and the scriptUrl to index.php (everything without any slashes).

Greetings Ralf

**Comment by Shnoulle** [comment]
I fix it in https://github.com/SondagesPro/LS-sendMailCron/commit/2123ff3421748c1f17c32ad424e8f396a19dd162#diff-8eae6e55c3698d0b1255f2f7feceff70R377 
and here after : https://github.com/SondagesPro/LS-sendMailCron/commit/8e1ce2a23d8423acea3879e9315b37bef84cfb99#diff-8eae6e55c3698d0b1255f2f7feceff70L896

Can you check if it's OK with the last version ?

Maybe an update in LS ...
